language:
  - go 
sudo: required

go:
  - "1.11"

before_install:
  - git config --global url."git@github.com:".insteadOf "https://github.com/"
  - wget "https://github.com/Masterminds/glide/releases/download/v0.13.2/glide-v0.13.2-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-v0.13.2-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH"

install: glide install -strip-vendor
script: 
  - make
