language:
  - go 
sudo: required
services: docker
go:
  - "1.11"

before_install:
#  - git config --global url."git@github.com:".insteadOf "https://github.com/"
  - wget "https://github.com/Masterminds/glide/releases/download/v0.13.2/glide-v0.13.2-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide-v0.13.2-linux-amd64.tar.gz
  - export PATH="$HOME/bin:$PATH"

install: glide install -strip-vendor
script: 
  - mkdir -p /home/travis/gopath/src/k8s.io/helm && cp * -a /home/travis/gopath/src/k8s.io/helm && cd /home/travis/gopath/src/k8s.io/helm && make docker-build VERSION="v2.13.1" && docker images

after_success:
    - docker images
#    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push $DOCKER_REPO
